= Quickstart
:idprefix:
:idseparator: -
:sectlinks:
:sectnums:
:toc: auto

:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-wireguard
:uri-rel-file-base: link:{uri-repo}/blob/main
:uri-rel-tree-base: link:{uri-repo}/tree/main
:uri-docs: {uri-rel-file-base}/docs
:uri-instructions: {uri-docs}/instructions.adoc
:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five
:uri-oci-okepolicy: https://docs.cloud.oracle.com/iaas/Content/ContEng/Concepts/contengpolicyconfig.htm#PolicyPrerequisitesService
:uri-oci-provider: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformproviderconfiguration.htm
:uri-oci-provider-precedence: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformproviderconfiguration.htm#terraformproviderconfiguration_topic-Order_of_Precedence
:uri-terraform: https://www.terraform.io
:uri-terraform-oci: https://www.terraform.io/docs/providers/oci/index.html
:uri-terraform-options: {uri-docs}/terraformoptions.adoc
:uri-terraform-precedence: https://www.terraform.io/docs/language/values/variables.html#variable-definition-precedence
:uri-variables: {uri-rel-file-base}/variables.tf
:uri-wireguard-ol: https://docs.oracle.com/en/operating-systems/oracle-linux/vpn/vpn-ConfiguringaVPNbyUsingWireGuard.html#vpn-wguard

== Assumptions

1. You have setup the {uri-oci-keys}[required keys]
2. You know the {uri-oci-ocids}[required OCIDs]
3. You have a WireGuard client installed

== Prerequisites

1. git is installed
2. ssh client is installed
3. Terraform 1.0.0+ is installed

== Provision using this git repo

. Clone the repo:

+
[source,bash]
----
git clone https://github.com/oracle-terraform-modules/terraform-oci-wireguard.git tfwg

cd tfwg
cp terraform.tfvars.example terraform.tfvars
----

=== Creating Providers

You need to create 2 providers:
.. 1 provider for the region where your WireGuard instance will be created
.. 1 provider for the home region. This is required for conducting identity operations. *Note that your home region may not necessarily be the same as your current region.*

. Create a provider.tf file in root add 2 providers:
+
----
provider "oci" {
  fingerprint      = var.api_fingerprint
  private_key_path = var.api_private_key_path
  region           = var.region
  tenancy_ocid     = var.tenancy_id
  user_ocid        = var.user_id
}

provider "oci" {
  fingerprint      = var.api_fingerprint
  private_key_path = var.api_private_key_path
  region           = var.home_region
  tenancy_ocid     = var.tenancy_id
  user_ocid        = var.user_id
  alias            = "home"
}
----


. You can also use providers ({uri-oci-provider}[using differerent methods]) such as:

.. config file profile
.. auth token
.. instance principal


. Set mandatory parameters in the provider depending on your {uri-oci-provider}[method of initializing your provider]:

+
----
tenancy_id = "replace.me"

# general oci parameters
compartment_id = "replace.me"
label_prefix   = "replace.me"

# ssh keys
ssh_public_key_path = "~/.ssh/id_rsa.pub"

availability_domain = 1

wireguard_access = ["anywhere"]

ig_route_id = "replace.me"

netnum = 3

newbits = 13

vcn_id = "replace.me"

wireguard_image_id = "Oracle"

wireguard_os_version = "9"

wireguard_shape = {
  shape="VM.Standard.E4.Flex",
  ocpus=2,
  memory=32,
  boot_volume_size=50
}

wireguard_state= "RUNNING"

wireguard_timezone = "Australia/Sydney"

wireguard_type = "public"

upgrade_wireguard = false
----

You can set those parameters using:

1. environment variables (e.g. TF_api_fingerprint)
2. a `terraform.tfvars` file

Please ensure you understand the {uri-terraform-precedence}[Terraform variable definition order of precedence] and {uri-oci-provider-precedence}[that of OCI].

. Run Terraform:

+
[source,bash]
----
terraform init
terraform plan
terraform apply
----

=== Configure WireGuard Tunnel

==== On the WireGuard client

. The above Terraform apply run will output something like:

----
[Peer]
PublicKey=
AllowedIPs=10.0.0.0/16
Endpoint=<public-ip>:51820
----

. ssh to the WireGuard host to obtain the public key:

+
----
ssh opc@<public-ip>
----

. Obtain the public key:

+
----
cat /home/opc/publickey

zyxw0987!@#$vuts6543
----

. Add or edit your local WireGuard client tunnel configuration and replace the public key and public IP address:

+
----
[Interface]
PrivateKey = abcd1234efgh5678
ListenPort = 60477
Address = 192.168.2.2/32

[Peer]
PublicKey = zyxw0987!@#$vuts6543
AllowedIPs = 10.0.0.0/16
Endpoint = <public-ip>:51820
----

. Also note your local public key

==== On the WireGuard server

. Edit the wireguard config file:

. Uncomment the peer configuration on the server in the file ```/etc/wireguard/wg0.conf```

+
----
# [Peer]
# PublicKey = CLIENT_PUBLIC_KEY
# AllowedIPs = 192.168.2.2/32
# Endpoint = CLIENT_PUBLIC_IP:60477
----

. Replace `CLIENT_PUBLIC_KEY` with your client's public key
. Replace `CLIENT_PUBLIC_IP` with your public IP address

. Start WireGuard

+
----
# wg-quick up wg0
----

== Related documentation

* {uri-wireguard-ol}[Configuring WireGuard on Oracle Linux]

* {uri-instructions}[Detailed Instructions]

* {uri-terraform-options}[All Terraform configuration options] for {uri-repo}[this project]
